
# cargo-vet audits file

[[audits.lexime-trie]]
who = "SAKAI, Kazuaki <kaz.july.7@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.1 -> 0.2.2"

[[audits.lexime-trie]]
who = "SAKAI, Kazuaki <kaz.july.7@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.2 -> 0.3.0"

[[audits.lexime-trie]]
who = "SAKAI, Kazuaki <kaz.july.7@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.0 -> 0.4.0"

[[audits.lexime-trie]]
who = "SAKAI, Kazuaki <kaz.july.7@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.5.0"

[[audits.rustls-webpki]]
who = "SAKAI, Kazuaki <kaz.july.7@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.103.9 -> 0.103.10"
