#!/usr/bin/env bash
# Tests for scripts/check-sources.sh, the screen's refusal of dependency
# sources it cannot vet. Run by CI's screen job, before the screen itself, and
# by `mise run test-check-sources`.
#
# Each case builds a fixture tree (engine/Cargo.lock, optional cargo configs)
# and runs the check from its root. The spelling cases are why the check
# parses TOML: each one passed a line pattern in #345 — an indented `source`,
# a quoted `["source".…]` table — and cargo reads them all the same way.
set -euo pipefail

repo=$(cd "$(dirname "$0")/.." && pwd)
check="$repo/scripts/check-sources.sh"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fails=0

CRATES_IO='registry+https://github.com/rust-lang/crates.io-index'

# A lockfile shaped like the real one: header, a workspace package (no
# source), and a crates.io package.
base_lock() {
  cat <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "lex-core"
version = "0.1.0"

[[package]]
name = "anyhow"
version = "1.0.104"
source = "$CRATES_IO"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
EOF
}

# fixture <extra lock text> [<config path> <config text>]: a fresh tree.
# (mktemp, not a counter: this runs in a $(...) subshell, which would lose it.)
fixture() {
  local dir
  dir=$(mktemp -d "$tmp/case.XXXXXX")
  mkdir -p "$dir/engine"
  { base_lock; printf '%s' "$1"; } >"$dir/engine/Cargo.lock"
  if [[ $# -ge 3 ]]; then
    mkdir -p "$dir/$(dirname "$2")"
    printf '%s' "$3" >"$dir/$2"
  fi
  echo "$dir"
}

# expect <name> <want exit: 0 or fail> <want line on stdout+stderr> <dir>
expect() {
  local name=$1 want=$2 line=$3 dir=$4 rc=0
  # $(fixture ...) is an argument, so set -e does not catch its failure; an
  # empty dir would otherwise run the case wherever this script stands.
  if [[ ! -d $dir ]]; then
    echo "FAIL $name"
    echo "     no fixture directory"
    fails=$((fails + 1))
    return
  fi
  (cd "$dir" && bash "$check") >"$tmp/out" 2>&1 || rc=$?
  if { [[ $want == 0 && $rc -eq 0 ]] || [[ $want == fail && $rc -ne 0 ]]; } &&
    grep -qF -- "$line" "$tmp/out"; then
    echo "ok   $name"
  else
    echo "FAIL $name"
    echo "     want: exit $want, a line containing: $line"
    echo "     got:  exit $rc, output: $(cat "$tmp/out")"
    fails=$((fails + 1))
  fi
}

GIT='git+https://example.com/evil#0123abcd'

# --- Cargo.lock ---
expect "crates.io only passes" 0 "sources: crates.io only" "$(fixture '')"
expect "the repository's own Cargo.lock passes" 0 "sources: crates.io only" "$repo"
expect "git source" fail "  - $GIT" "$(fixture "
[[package]]
name = \"evil\"
version = \"0.1.0\"
source = \"$GIT\"
")"
expect "indented git source (#345)" fail "  - $GIT" "$(fixture "
[[package]]
  name = \"evil\"
  version = \"0.1.0\"
  source = \"$GIT\"
")"
expect "quoted source key" fail "  - $GIT" "$(fixture "
[[package]]
name = \"evil\"
version = \"0.1.0\"
\"source\" = \"$GIT\"
")"
expect "other registry" fail "  - sparse+https://other.example/index/" "$(fixture '
[[package]]
name = "evil"
version = "0.1.0"
source = "sparse+https://other.example/index/"
')"
expect "patch.unused git source" fail "  - $GIT" "$(fixture "
[[patch.unused]]
name = \"evil\"
version = \"0.1.0\"
source = \"$GIT\"
")"
missing=$(fixture '')
rm "$missing/engine/Cargo.lock"
expect "missing Cargo.lock" fail "Cargo.lock" "$missing"

# --- cargo configs: every spelling of a [source] table is refused ---
for cfg in engine/.cargo/config.toml .cargo/config.toml .cargo/config engine/.cargo/config; do
  expect "$cfg: [source.crates-io]" fail "sources: $cfg sets source," \
    "$(fixture '' "$cfg" $'[source.crates-io]\nreplace-with = "mirror"\n')"
done
C=engine/.cargo/config.toml
expect "quoted table (#345)" fail "sources: $C sets source," \
  "$(fixture '' "$C" $'["source".crates-io]\nreplace-with = "mirror"\n')"
expect "indented table header" fail "sources: $C sets source," \
  "$(fixture '' "$C" $'  [source.crates-io]\n  replace-with = "mirror"\n')"
expect "dotted key" fail "sources: $C sets source," \
  "$(fixture '' "$C" $'source.crates-io.replace-with = "mirror"\n')"
expect "inline table" fail "sources: $C sets source," \
  "$(fixture '' "$C" $'source = { crates-io = { replace-with = "mirror" } }\n')"
expect "config that does not parse" fail "does not parse as TOML" \
  "$(fixture '' "$C" $'[source\n')"
expect "config without [source] passes" 0 "sources: crates.io only" \
  "$(fixture '' "$C" $'[build]\nrustflags = []\n[alias]\nt = "test"\n')"

# --- other keys that move dependencies: refused by the allowlist ---
inc=$(fixture '' "$C" $'include = ["mirror.toml"]\n')
printf '[source.crates-io]\nreplace-with = "v"\n[source.v]\ndirectory = "vendor"\n' >"$inc/engine/.cargo/mirror.toml"
expect "include of a file that replaces a source" fail "sets include," "$inc"
expect "config [patch] with a git crate" fail "sets patch," \
  "$(fixture '' "$C" $'[patch.crates-io]\nfoo = { git = "https://example.com/foo" }\n')"
expect "paths override" fail "sets paths," "$(fixture '' "$C" $'paths = ["../foo"]\n')"
expect "registries table" fail "sets registries," \
  "$(fixture '' "$C" $'[registries.evil]\nindex = "sparse+https://evil.example/"\n')"
expect "unknown key" fail "sets some-future-key," "$(fixture '' "$C" $'some-future-key = 1\n')"

if [[ $fails -gt 0 ]]; then
  echo "check-sources-test: $fails failed"
  exit 1
fi
echo "check-sources-test: all passed"
