#!/usr/bin/env bash
# Generate the test runner's dispatch from the test sources themselves.
#
# `TestRunner.main()` used to call each test by hand. That list was the same
# hazard as the hand-maintained source list #316 was about: a test could be
# written, compiled, and simply never called — green CI, author believes it is
# covered. axes.md rates a silently-skipped test CRITICAL.
#
# The first attempt at closing it was a checker that diffed the definitions
# against the hand-written call list. That is a reconciler between two
# human-maintained artifacts — the shape CLAUDE.md rules out — and it inherited
# the usual weaknesses: it passed vacuously when its pattern matched nothing,
# and it counted a name mentioned in a comment as a call. Generating the list
# instead deletes both, because there is no second artifact to disagree with.
#
# The residual is the pattern itself: a declaration form the generator does not
# recognise would not be dispatched, silently. That is what the broad-vs-strict
# check below closes — it is a self-check on one derivation, not a reconcile,
# and it fails closed.
#
# The real canonical form is XCTest / swift-testing, which discovers tests
# through the objc runtime and needs no generator at all. Deferred: it would
# rewrite every test file and link XCTest into a runner that deliberately
# stays headless. Revisit if a test ever legitimately needs a declaration form
# this generator cannot emit a call for, or if a second dispatch list appears.
set -euo pipefail

out=${1:?usage: test-dispatch.sh <output.swift>}
here=$(dirname "$0")
sources=$(bash "$here/swift-sources.sh" Tests)

# Line comments are stripped first. Prose about tests is common in this repo
# — the runner's own doc comment says `func testX()` — and without this the
# broad pattern below trips on it. (Block comments are not stripped; there are
# none under Tests/, and a false trip fails closed with a readable message
# rather than dispatching wrongly.)
code=$(printf '%s\n' "$sources" | xargs cat | sed -E 's://.*::')

# Strict: declarations we can safely emit a call for — top level, no attributes
# or modifiers, no parameters. Whitespace is `[[:space:]]+` to match the broad
# pattern below: any difference between the two stops the whole suite, so the
# two must not disagree over something as incidental as a second space.
# `|| true` because "no match" is answered by the explicit emptiness check
# below, with a better message than a bare exit 1.
strict=$(printf '%s\n' "$code" \
  | grep -oE '^func[[:space:]]+test[A-Za-z0-9_]*\(\)' \
  | sed -E 's/^func[[:space:]]+//; s/\(\)$//' | sort -u || true)

# Broad: anything that reads as a test declaration in any form — indented, or
# behind `private` / `@MainActor` / any other attribute, or taking parameters.
broad=$(printf '%s\n' "$code" \
  | grep -oE 'func[[:space:]]+test[A-Za-z0-9_]*' \
  | sed -E 's/.*func[[:space:]]+//' | sort -u || true)

if [ -z "$strict" ]; then
  echo "test-dispatch: no dispatchable 'func testX()' found under Tests/ —" >&2
  echo "  refusing to generate an empty run" >&2
  exit 1
fi

# Anything the broad pattern sees and the strict one does not would compile but
# never run. Fail rather than emit a dispatch that quietly omits it.
missed=$(comm -13 <(printf '%s\n' "$strict") <(printf '%s\n' "$broad"))
if [ -n "$missed" ]; then
  echo "test-dispatch: these read as tests but cannot be dispatched" >&2
  echo "$missed" | sed 's/^/  /' >&2
  echo "  If it is a helper rather than a test, rename it off the 'test'" >&2
  echo "  prefix — that is the usual cause. If it is a test, give it the" >&2
  echo "  plain top-level 'func testX()' form. Widening this generator is a" >&2
  echo "  last resort: it may only emit calls that compile, so a declaration" >&2
  echo "  taking parameters can never be admitted here." >&2
  exit 1
fi

mkdir -p "$(dirname "$out")"
{
  echo "// Generated by scripts/test-dispatch.sh. Do not edit, do not commit."
  echo "func runAllDiscoveredTests() {"
  printf '%s\n' "$strict" | sed 's/^/    /; s/$/()/'
  echo "}"
} > "$out"

echo "test-dispatch: $(printf '%s\n' "$strict" | wc -l | tr -d ' ') tests dispatched"
